# Generated by Django 5.2.3 on 2025-07-07 14:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dpt_name",
                    models.CharField(
                        choices=[
                            ("Sales", "Sales"),
                            ("Marketing", "Marketing"),
                            ("Human Resources", "Human Resources"),
                            ("Finance", "Finance"),
                            ("Information Technology", "Information Technology"),
                            ("Operations", "Operations"),
                            ("Customer Service", "Customer Service"),
                            ("Legal", "Legal"),
                            ("Procurement", "Procurement"),
                            ("Research and Development", "Research and Development"),
                            ("Logistics", "Logistics"),
                            ("Administration", "Administration"),
                            ("Engineering", "Engineering"),
                            ("Production", "Production"),
                            ("Quality Assurance", "Quality Assurance"),
                            ("Business Development", "Business Development"),
                            ("Public Relations", "Public Relations"),
                            ("Training and Development", "Training and Development"),
                            ("Security", "Security"),
                            ("Compliance", "Compliance"),
                        ],
                        max_length=200,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "extension_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["dpt_name"],
            },
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("job_department", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time"),
                            ("PT", "Part-time"),
                            ("CT", "Contract"),
                            ("IN", "Internship"),
                            ("TP", "Temporary"),
                            ("FR", "Freelance"),
                        ],
                        default="FT",
                        max_length=2,
                    ),
                ),
                (
                    "job_salary_range",
                    models.CharField(
                        blank=True,
                        help_text="Example: $40,000 - $60,000",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "requirements",
                    models.TextField(
                        default=None, help_text="List required skills or qualifications"
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        default=None, help_text="List core job responsibilities"
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(default="example@email.com", max_length=254),
                ),
                ("is_remote", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("fname", models.CharField(max_length=200, verbose_name="First Name")),
                ("lname", models.CharField(max_length=200, verbose_name="Last Name")),
                ("sname", models.CharField(max_length=200, verbose_name="Surname")),
                ("employee_dob", models.DateTimeField(auto_now_add=True)),
                (
                    "employee_phonenumber",
                    models.IntegerField(
                        default=0, help_text="contributors personal phone number"
                    ),
                ),
                (
                    "employee_profession",
                    models.CharField(
                        choices=[
                            ("Accountant", "Accountant"),
                            ("Architect", "Architect"),
                            ("Artist", "Artist"),
                            ("Chef", "Chef"),
                            ("Consultant", "Consultant"),
                            ("Data Analyst", "Data Analyst"),
                            ("Data Scientist", "Data Scientist"),
                            ("Dentist", "Dentist"),
                            ("Developer", "Developer"),
                            ("Doctor", "Doctor"),
                            ("Engineer", "Engineer"),
                            ("Financial Analyst", "Financial Analyst"),
                            ("Graphic Designer", "Graphic Designer"),
                            ("HR Manager", "HR Manager"),
                            ("Journalist", "Journalist"),
                            ("Lawyer", "Lawyer"),
                            ("Lecturer", "Lecturer"),
                            ("Manager", "Manager"),
                            ("Marketing Specialist", "Marketing Specialist"),
                            ("Mechanic", "Mechanic"),
                            ("Nurse", "Nurse"),
                            ("Pharmacist", "Pharmacist"),
                            ("Photographer", "Photographer"),
                            ("Pilot", "Pilot"),
                            ("Product Manager", "Product Manager"),
                            ("Project Manager", "Project Manager"),
                            ("Psychologist", "Psychologist"),
                            ("Sales Executive", "Sales Executive"),
                            ("Senior Engineer", "Senior Engineer"),
                            ("Software Engineer", "Software Engineer"),
                            ("Teacher", "Teacher"),
                            ("UX Designer", "UX Designer"),
                            ("Veterinarian", "Veterinarian"),
                            ("Web Developer", "Web Developer"),
                            ("Writer", "Writer"),
                        ],
                        help_text="Career or professional designation",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(choices=[("Kenya", "Kenya")], max_length=50),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "employee_ID",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Contract", "Contract"),
                            ("Intern", "Intern"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_joined", models.DateField()),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("On Leave", "On Leave"),
                            ("Terminated", "Terminated"),
                            ("Resigned", "Resigned"),
                            ("Retired", "Retired"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pay_grade", models.CharField(blank=True, max_length=50, null=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_account_number", models.CharField(max_length=50)),
                (
                    "tax_id_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nhif_number", models.CharField(blank=True, max_length=50, null=True)),
                ("nssf_number", models.CharField(blank=True, max_length=50, null=True)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_relation", models.CharField(max_length=50)),
                ("emergency_contact_phone", models.CharField(max_length=15)),
                ("id_number", models.CharField(max_length=50)),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "contract_file",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="ElevateHRApp.department",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="ElevateHRApp.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="incharge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="ElevateHRApp.employee",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("attendance_check_in", models.TimeField(blank=True, null=True)),
                ("attendance_check_out", models.TimeField(blank=True, null=True)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Leave", "Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "attendance_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ElevateHRApp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Sick", "Sick"),
                            ("Annual", "Annual"),
                            ("Maternity", "Maternity"),
                            ("Emergency", "Emergency"),
                        ],
                        max_length=50,
                    ),
                ),
                ("leave_start_date", models.DateField()),
                ("leave_end_date", models.DateField()),
                ("leave_reason", models.TextField()),
                (
                    "leave_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "leave_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ElevateHRApp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payroll_date", models.DateField()),
                (
                    "payroll_basic_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payroll_deductions",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payroll_net_pay",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payroll_paid_status", models.BooleanField(default=False)),
                (
                    "payroll_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ElevateHRApp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performance_review_date", models.DateField()),
                ("performance_reviewer", models.CharField(max_length=100)),
                ("performance_rating", models.IntegerField()),
                ("performance_comments", models.TextField()),
                (
                    "performance_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ElevateHRApp.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_title", models.CharField(max_length=100)),
                ("training_description", models.TextField()),
                ("training_trainer", models.CharField(max_length=100)),
                ("training_date", models.DateField()),
                (
                    "training_attendees",
                    models.ManyToManyField(to="ElevateHRApp.employee"),
                ),
            ],
        ),
    ]
