# Generated by Django 5.2.3 on 2025-07-07 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevateHRApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time"),
                            ("PT", "Part-time"),
                            ("CT", "Contract"),
                            ("IN", "Internship"),
                            ("TP", "Temporary"),
                            ("FR", "Freelance"),
                        ],
                        default="FT",
                        max_length=2,
                    ),
                ),
                (
                    "job_salary_range",
                    models.CharField(
                        blank=True,
                        help_text="Example: $40,000 - $60,000",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "requirements",
                    models.TextField(
                        default=None, help_text="List required skills or qualifications"
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        default=None, help_text="List core job responsibilities"
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(default="example@email.com", max_length=254),
                ),
                ("is_remote", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "job_department",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ElevateHRApp.department",
                    ),
                ),
            ],
        ),
    ]
