# Generated by Django 5.2.3 on 2025-06-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElevateHRApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('attendance_check_in', models.TimeField(blank=True, null=True)),
                ('attendance_check_out', models.TimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=20)),
                ('attendance_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElevateHRApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, unique=True)),
                ('job_description', models.TextField()),
                ('job_salary_range', models.CharField(max_length=100)),
                ('job_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElevateHRApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick'), ('Annual', 'Annual'), ('Maternity', 'Maternity'), ('Emergency', 'Emergency')], max_length=50)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_reason', models.TextField()),
                ('leave_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('leave_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElevateHRApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_date', models.DateField()),
                ('payroll_basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payroll_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payroll_net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payroll_paid_status', models.BooleanField(default=False)),
                ('payroll_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElevateHRApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_review_date', models.DateField()),
                ('performance_reviewer', models.CharField(max_length=100)),
                ('performance_rating', models.IntegerField()),
                ('performance_comments', models.TextField()),
                ('performance_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElevateHRApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=100)),
                ('training_description', models.TextField()),
                ('training_trainer', models.CharField(max_length=100)),
                ('training_date', models.DateField()),
                ('training_attendees', models.ManyToManyField(to='ElevateHRApp.employee')),
            ],
        ),
    ]
