# Generated by Django 5.2.3 on 2025-07-07 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevateHRApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposition",
            name="job_department",
            field=models.ForeignKey(
                max_length=255,
                on_delete=django.db.models.deletion.CASCADE,
                to="ElevateHRApp.department",
            ),
        ),
    ]
