# Generated by Django 5.2.3 on 2025-07-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevateHRApp", "0002_jobposting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_ID",
            field=models.CharField(
                default=0,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
