# Generated by Django 5.2.3 on 2025-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ElevateHRApp", "0003_alter_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
