# Generated by Django 5.2.3 on 2025-07-09 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ElevateHRApp", "0004_alter_employee_employee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_period_start", models.DateField()),
                ("pay_period_end", models.DateField()),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Generated", "Generated"),
                            ("Paid", "Paid"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total allowances",
                        max_digits=10,
                    ),
                ),
                (
                    "bonuses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Bonuses for the pay period",
                        max_digits=10,
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "income_tax",
                    models.DecimalField(
                        decimal_places=2, default=0.0, help_text="PAYE", max_digits=10
                    ),
                ),
                (
                    "nssf_deduction",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "nhif_deduction",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "other_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="e.g., salary advance, loans",
                        max_digits=10,
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="ElevateHRApp.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payslip",
                "verbose_name_plural": "Payslips",
                "ordering": ["-pay_period_end", "employee"],
            },
        ),
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disbursement_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Successful", "Successful"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(default="Bank Transfer", max_length=50),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                (
                    "payslip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursement",
                        to="ElevateHRApp.payslip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disbursement",
                "verbose_name_plural": "Disbursements",
                "ordering": ["-disbursement_date"],
            },
        ),
        migrations.DeleteModel(
            name="Payroll",
        ),
    ]
